=== mattrei/curriculum-at-pdf-to-xml/schema/LearningStandardDocument.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="https://www.vroodl.es/datamodel/1.x"
	elementFormDefault="qualified"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="https://www.vroodl.es/datamodel/1.x">

	<xsd:include schemaLocation="Common.xsd"></xsd:include>
	<xsd:annotation>
		<xsd:documentation>
			A curriculum standards document or the like published by a
			national, state, district, school site, professional
			association or other interested party. The
			LearningStandardDocument reflects an expectation of student
			work.
		</xsd:documentation>
	</xsd:annotation>




	<xsd:complexType name="TitleListType">
		<xsd:sequence minOccurs="0" maxOccurs="unbounded">
			<xsd:element name="Title" type="xsd:normalizedString"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="CurriculumStructuresRefIdListType">
		<xsd:sequence>
			<xsd:element name="CurriculumStructureRefId"
				type="IdRefType" minOccurs="0" maxOccurs="unbounded">
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>





	<xsd:complexType name="CopyrightType">
		<xsd:sequence>
			<xsd:element name="Holder" type="xsd:normalizedString"></xsd:element>
			<xsd:element name="Date" type="xsd:date"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>



	<xsd:complexType name="LearningObjectiveListType">
		<xsd:sequence>
			<xsd:element name="LearningObjective" type="xsd:string"
				minOccurs="0" maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>
						"Teach students about the basics of cellular
						structure and lifecycle."
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>





	<xsd:complexType name="LearningStandardItemRefIdListType">
		<xsd:annotation>
			<xsd:documentation>
				Associated LearningStandardItem objects.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="LearningStandardItemRefId"
				type="IdRefType">
				<xsd:annotation>
					<xsd:documentation>
						Link to associated LearningStandardItem object.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>


	<xsd:complexType name="CurriculumStructureType">
		<xsd:annotation>
			<xsd:documentation>
				An object designed to contain instructional objects such
				as units, lessons, activities, and assessments—or other
				containers—joined together under a particular topic
				and/or duration.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="RefId" type="RefIdType"></xsd:element>
			<xsd:element name="Titles" type="TitleListType"
				minOccurs="0" maxOccurs="unbounded">
			</xsd:element>
			<xsd:element name="Description" type="xsd:string"
				nillable="true" minOccurs="0" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>
						Description of this curriculum object
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="LearningObjectives"
				type="LearningObjectiveListType" minOccurs="0">
			</xsd:element>
			<xsd:element name="LearningStandards"
				type="LearningStandardItemRefIdListType" nillable="true"
				minOccurs="0" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>
						Associated learning standards.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="CurriculumHierarchyLevel"
				type="CurriculumStructureCurriculumHierarchyLevelType" minOccurs="0"
				maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>
						Describes the position of this object in the
						curriculum hierarchy.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>

			<xsd:element name="GradeLevel" type="GradeLevelType"
				minOccurs="0" maxOccurs="1">
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="CurriculumStructureCollectionType">
		<xsd:sequence>
			<xsd:element name="CurriculumStructure"
				type="CurriculumStructureType" minOccurs="0"
				maxOccurs="unbounded">
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType
		name="CurriculumStructureCurriculumHierarchyLevelType">
		<xsd:sequence>
			<xsd:element name="Number" type="xsd:unsignedInt"
				minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						Integer assigned to each hierarchical level
						within the CurriculumStructure tree. The top
						level is 1.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Name" type="xsd:normalizedString"
				minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						Used to describe what role this is serving in
						the structure. Some curriculum objects describe
						their levels in terms of programs of study,
						courses and units. Others use other terms. This
						attribute names the level of the item.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Description" type="xsd:string"
				minOccurs="0">
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="LearningStandardDocumentType">
		<xsd:sequence>
			<xsd:element name="RefId" type="RefIdType"></xsd:element>
			<xsd:element name="RefURI" type="xsd:anyURI">
				<xsd:annotation>
					<xsd:documentation>
						A URI that establishes uniqueness of the object
						instance.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>

			<xsd:element name="LocalAdoptionDate" type="xsd:date">
				<xsd:annotation>
					<xsd:documentation>
						The date the local organization adopted this
						standard document
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>

			<xsd:element name="EndOfLifeDate" type="xsd:date"></xsd:element>


			<xsd:element name="Description" type="xsd:string"></xsd:element>

			<xsd:element name="YearCreated" type="xsd:gYear"></xsd:element>

			<xsd:element name="Source" type="xsd:token"></xsd:element>

			<xsd:element name="Copyright" type="CopyrightType"></xsd:element>

			<xsd:element name="DocumentDate" type="xsd:date">
				<xsd:annotation>
					<xsd:documentation>
						The date the current status was achieved.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>

			<xsd:element name="DocumentStatus" type="xsd:token"></xsd:element>

			<xsd:element name="OrganizationContactPoint"
				type="xsd:string">
				<xsd:annotation>
					<xsd:documentation>
						A brief description of how to contact the
						organization maintaining the standards. It could
						be a phone number, email address, or URL.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>

			<xsd:element name="Title" type="xsd:normalizedString"></xsd:element>
			<xsd:element name="GradeLevels" type="GradeLevelsType">
				<xsd:annotation>
					<xsd:documentation>
						A common element used to specify the collection
						of grade levels supported.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>

			<xsd:element name="CurriculumStructures"
				type="CurriculumStructureCollectionType">
			</xsd:element>

			<xsd:element name="Reference" type="ReferenceType"></xsd:element>

			<xsd:element name="DocumentVersion" type="xsd:token">
				<xsd:annotation>
					<xsd:documentation>
						Identifies the version of the document that this
						object instance represents. Note that new
						versions of documents must generate new RefIds
						and therefore a new object instance. This
						element is immutable in that once the object has
						been published with a value (other than blank)
						it must never be changed.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="ExtendedElements" type="ExtendedElementsType" minOccurs="0" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>A name/value pair, the name being contained in the Name attribute, the value being the element content.</xsd:documentation></xsd:annotation></xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="LearningStandardDocument"
		type="LearningStandardDocumentType">
	</xsd:element>



</xsd:schema>

=== mattrei/curriculum-at-pdf-to-xml/xml/gw_unterstufe_OLD.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:LearningStandardDocument
	xmlns:p="https://www.vroodl.es/datamodel/1.x"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://www.vroodl.es/datamodel/1.x ../schema/LearningStandardDocument.xsd ">
	<p:RefId>ae4990cd6db34ab8a4f5ebed475823f8</p:RefId>
	<p:RefURI></p:RefURI>
	<p:LocalAdoptionDate>2019-08-15</p:LocalAdoptionDate>
	<p:EndOfLifeDate>2019-08-15</p:EndOfLifeDate>
	<p:Description>Lehrplan 2000 der HS/NMS und AHS-Unterstufe</p:Description>
	<p:YearCreated>2000</p:YearCreated>
	<p:Source></p:Source>
	<p:Copyright>
		<p:Holder>Matthias Treitler</p:Holder>
		<p:Date>2019-08-15</p:Date>
	</p:Copyright>
	<p:DocumentDate>2019-08-15</p:DocumentDate>
	<p:DocumentStatus>ready</p:DocumentStatus>
	<p:OrganizationContactPoint></p:OrganizationContactPoint>
	<p:Title>Geographie und Wirtschaftskunde</p:Title>
	<p:GradeLevels>
		<p:GradeLevel>
			<p:Code>1</p:Code>
		</p:GradeLevel>
		<p:GradeLevel>
			<p:Code>2</p:Code>
		</p:GradeLevel>
		<p:GradeLevel>
			<p:Code>3</p:Code>
		</p:GradeLevel>
		<p:GradeLevel>
			<p:Code>4</p:Code>
		</p:GradeLevel>
	</p:GradeLevels>
	<p:CurriculumStructures>
		<p:CurriculumStructure>
			<p:RefId>124db9cb0c004563922b61e15f519bd8</p:RefId>
			<p:Titles>
				<p:Title>Ein Blick auf die Erde</p:Title>
			</p:Titles>
			<p:LearningObjectives>
				<p:LearningObjective>Erwerben grundlegender Informationen über die Erde mit Globus, Karten, Atlas und Bildern.</p:LearningObjective>
			</p:LearningObjectives>
			<p:CurriculumHierarchyLevel>
				<p:Number>1</p:Number></p:CurriculumHierarchyLevel>
			<p:GradeLevel>
				<p:Code>1</p:Code>
			</p:GradeLevel>
		</p:CurriculumStructure>
		<p:CurriculumStructure>
			<p:RefId>60c53b8891024c7ca7c7c8a054a5d880</p:RefId>
			<p:Titles>
				<p:Title>Wie Menschen in unterschiedlichen Gebieten der Erde leben und
					wirtschaften</p:Title>
			</p:Titles>
			<p:LearningObjectives>
				<p:LearningObjective>Erkennen, dass sich Menschen in ihren Lebens- und Konsumgewohnheiten auf regionale und kulturelle Voraussetzungen einstellen und dass die Lebensweise einem Wandel unterliegt.</p:LearningObjective>
				<p:LearningObjective>Erkennen, wie einfache Wirtschaftsformen von Natur- und Gesellschaftsbedingungen beeinflusst werden, und erfassen, dass Menschen unterschiedliche, sich verändernde Techniken und Produktionsweisen anwenden.</p:LearningObjective>
				<p:LearningObjective>Erkennen, wie Menschen mit Naturgefahren umgehen.</p:LearningObjective>
			</p:LearningObjectives>
			<p:CurriculumHierarchyLevel>
				<p:Number>2</p:Number></p:CurriculumHierarchyLevel>
			<p:GradeLevel>
				<p:Code>1</p:Code>
			</p:GradeLevel>
		</p:CurriculumStructure>
		<p:CurriculumStructure>
			<p:RefId>729e89ec9ced4d1c9ed3d0cc1f7cccb3</p:RefId>
			<p:Titles>
				<p:Title>Wie Menschen Rohstoffe und Energie gewinnen und nutzen</p:Title>
			</p:Titles>
			<p:LearningObjectives>
				<p:LearningObjective>Erkennen, wie Rohstoffe und Nutzenergie gewonnen und zu den Verbraucherinnen und Verbrauchern gebracht werden.</p:LearningObjective>
				<p:LearningObjective>Einsehen, dass Rohstoffe und Energieträger auf der Erde ungleichmäßig verteilt und begrenzt vorhanden sind und dass ihre Nutzung oft die Umwelt belastet.</p:LearningObjective>
			</p:LearningObjectives>
			<p:CurriculumHierarchyLevel>
				<p:Number>3</p:Number></p:CurriculumHierarchyLevel>
			<p:GradeLevel>
				<p:Code>1</p:Code>
			</p:GradeLevel>
		</p:CurriculumStructure>
		<p:CurriculumStructure>
			<p:RefId>965910087b564602b006d869288746dc</p:RefId>
			<p:Titles>
				<p:Title>Ein erster Überblick</p:Title></p:Titles>
			<p:LearningObjectives>
				<p:LearningObjective>Regionale bzw. zonale Einordnung der im Unterricht durchgenommenen Beispiele.</p:LearningObjective>
				<p:LearningObjective>Erkennen der Grundstrukturen einfacher Wirtschaftsformen: von der agrarisch dominierten Selbstversorgerwirtschaft zu arbeitsteiligen Systemen.

</p:LearningObjective>
				<p:LearningObjective>Erfassen, dass es auf der Erde eine Regelhaftigkeit in der Anordnung klimatischer Erscheinungen gibt.</p:LearningObjective></p:LearningObjectives>
			<p:CurriculumHierarchyLevel>
				<p:Number>4</p:Number></p:CurriculumHierarchyLevel>
			<p:GradeLevel>
				<p:Code>1</p:Code>
			</p:GradeLevel>
		</p:CurriculumStructure>
	</p:CurriculumStructures>
	<p:Reference>
		<p:MIMEType>HTML</p:MIMEType>
		<p:Description></p:Description>
		<p:URL>https://www.ris.bka.gv.at/GeltendeFassung.wxe?Abfrage=Bundesnormen&Gesetzesnummer=10008568</p:URL>
	</p:Reference>
	<p:DocumentVersion>1</p:DocumentVersion>
</p:LearningStandardDocument>
